-- REPARO FINAL DA TABELA ESTOQUE (v2.2)
DO $$ 
BEGIN
    -- 1. Garante que o ID seja gerado automaticamente (Auto-incremento)
    ALTER TABLE public.estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN OTHERS THEN 
    RAISE NOTICE 'ID já possui auto-incremento.';
END $$;

-- 2. Sincroniza o contador de IDs com os dados já existentes
SELECT setval(
    pg_get_serial_sequence('public.estoque', 'id'),
    COALESCE(MAX(id), 0) + 1,
    false
) FROM public.estoque;

-- 3. Adiciona restrição ÚNICA na coluna nome (necessário para o upsert)
-- Se já houver duplicados, o comando abaixo pode falhar. 
-- O ideal é que a tabela esteja vazia ou com nomes únicos.
ALTER TABLE public.estoque ADD CONSTRAINT estoque_nome_unique UNIQUE (nome);

-- 4. Garante que todas as colunas necessárias existam
ALTER TABLE estoque 
ADD COLUMN IF NOT EXISTS nome TEXT,
ADD COLUMN IF NOT EXISTS quantidade DECIMAL(10,3) DEFAULT 0,
ADD COLUMN IF NOT EXISTS modo_estocagem VARCHAR(50) DEFAULT 'un',
ADD COLUMN IF NOT EXISTS custo DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS preco_venda DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS foto_url TEXT,
ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ DEFAULT NOW();

-- 5. Libera o acesso para salvamento
ALTER TABLE estoque DISABLE ROW LEVEL SECURITY;

-- Dica: Após rodar este comando, recarregue a página de estoque no site.
