-- SQL FINAL E DEFINITIVO PARA REPARAR A TABELA 'ESTOQUE'
-- Execute este comando no SQL Editor do seu projeto Supabase

-- 1. Garante que o ID seja auto-incremento (Identity)
DO $$ 
BEGIN
    ALTER TABLE public.estoque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION WHEN OTHERS THEN 
    RAISE NOTICE 'ID já possui identity ou erro ignorado.';
END $$;

-- 2. Sincroniza a contagem do ID (Resolve erro de Duplicate Key)
-- Isso faz com que o próximo ID gerado seja maior que o maior ID existente.
SELECT setval(
    pg_get_serial_sequence('public.estoque', 'id'),
    COALESCE(MAX(id), 0) + 1,
    false
) FROM public.estoque;

-- 3. Garante que todas as colunas necessárias existam
ALTER TABLE estoque 
ADD COLUMN IF NOT EXISTS nome TEXT,
ADD COLUMN IF NOT EXISTS quantidade DECIMAL(10,3) DEFAULT 0,
ADD COLUMN IF NOT EXISTS modo_estocagem VARCHAR(50) DEFAULT 'un',
ADD COLUMN IF NOT EXISTS custo DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS preco_venda DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS foto_url TEXT,
ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ DEFAULT NOW();

-- 4. Libera o acesso para salvamento
ALTER TABLE estoque DISABLE ROW LEVEL SECURITY;

-- Dica: Após rodar este comando, recarregue a página de estoque no site.
